#!/usr/bin/env python2
# coding=utf-8
# Name:			fromoA.py
# Function:		Analyzer - analyzes the fromo log and generates some kind of report
# URL:          https://github.com/yafp/fromo
# Date:			20160603
# Author: 		https://github.com/yafp/
#               http://yafp.de
#
# Resources:
#               http://stackoverflow.com/questions/26485621/read-a-text-file-in-python-line-wise


####################################
# CONSTANT
####################################
version = 20160603.01


####################################
# IMPORTS
####################################
import datetime     # for timestamp handling
import os
import sys

from clint.textui import colored, puts  # for colored text


####################################
# ARRAY DEFINITION
####################################
arrNewLines = []
arrDates = []
arrCommands = []
arrTitles = []
arrPIDs = []


####################################
# READING LOG
####################################
if sys.platform == "linux" or sys.platform == "linux2": # check if platform is supported or not
    os.system('clear')  # # clear the screen

    print " ___                   _____ "
    print "|  _|___ ___ _____ ___|  _  |"
    print "|  _|  _| . |     | . |     |"
    print "|_| |_| |___|_|_|_|___|__|__|    Version:"+str(version)+"\n"

    print "Starting reading log ..."
    fromolLogFile = open("fromoL.log" , "r") # open the log file

    # read it linewise
    for line in fromolLogFile.readlines():
        firstTwoChars = line[:2] # First 2 chars of line
        otherChars = line[2:] # Char 3 to end of line

        if firstTwoChars == '##':
            arrNewLines.append(otherChars)
        elif firstTwoChars == "D:":
            arrDates.append(otherChars)
        elif firstTwoChars == "C:":
            arrCommands.append(otherChars)
        elif firstTwoChars == "T:":
            arrTitles.append(otherChars)
        elif firstTwoChars == "P:":
            arrPIDs.append(otherChars)
        else:
            print "+++++ Unexpected log content - Please report at https://github.com/yafp/fromo/issues ++++++"

    fromolLogFile.close() # close the log file
    print "Finished reading log (arrays are filled)"


    ####################################
    # WRITING REPORT
    ####################################
    print "\nStarting HTML generation..."

    # Generate a timestamp
    d = datetime.datetime.now()
    dateString = str(d)

    #writepath = 'some/path/to/file.txt'
    writepath = dateString+'.html'

    mode = 'a' if os.path.exists(writepath) else 'w'
    with open(writepath, mode) as f:
        f.write('<html>\n')
        # html head
        f.write('<head>\n')
        f.write('<title>fromoAnalyzer Report</title>\n')
        f.write('<script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>')
        f.write('<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css">')
        f.write('<script type="text/javascript" src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>')
        f.write('<script>$( document ).ready(function() {$(\'#example\').DataTable();});</script>')
        f.write('</head>\n')
        # html body
        f.write('<body>\n')
        f.write('<h1>fromoAnalyzer Report</h1>\n')
        f.write('<table id="example" class="display" cellspacing="0" width="100%">\n')
        f.write('<thead><tr><th>Timestamp</th><th>Command</th><th>Title</th><th>PID</th></tr></thead>\n')
        f.write('<tbody>\n')
        # prepare array iteration
        aD = iter(arrDates)
        aC = iter(arrCommands)
        aT = iter(arrTitles)
        aP = iter(arrPIDs)
        # loop over the arrays
        for x in range(0, len(arrDates)):
            f.write('<tr><td>'+aD.next()+'</td><td>'+aC.next()+'</td><td>'+aT.next()+'</td><td>'+aP.next()+'</td></tr>\n')
        f.write('</tbody>\n')
        f.write('<tfoot><tr><th>Timestamp</th><th>Command</th><th>Title</th><th>PID</th></tr></tfoot>\n')
        f.write('</table>\n')
        f.write('<hr>\n')
        f.write('<p><small><center>Generated by <a href="https://github.com/yafp/fromo">fromo</a> at '+dateString+'</center></small></p>')
        f.write('</body>\n')
        f.write('</html>\n')
    f.close()
    print "Finished HTML generation"

else:
    puts(colored.red('[FAILED]')+'\tUnsupported operating system, aborting')
    sys.exit()
